baseURL = 'https://abhijariwala.netlify.app/'
languageCode = 'en-us'
title = 'Abhi Jariwala'
theme = "hugo-theme-codex-master"

[params]
  linkedin = "https://www.linkedin.com/in/abhishek-jariwala1/"
  github = "https://github.com/AbhishekJariwala"
  # ...

  iconOrder = ["Linkedin", "GitHub"]

  [[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

  [[menu.main]]
  identifier = "resume"
  name = "resume"
  title = "Resume"
  url = "/resume"